services:
  - type: web
    name: next-js
    runtime: node
    plan: starter
    buildCommand: ./render-cache-test.sh && pnpm install && pnpm build
    startCommand: pnpm start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
